name: Buildroot PC-UEFI x86_64 CI

on:
  workflow_dispatch:        # 手动触发
  push:
    paths:
      - 'seed.config'       # 只有 seed.config 变动才触发
  schedule:
    - cron: '0 2 * * 0'    # 每周日凌晨 2 点自动编译

env:
  REPO_URL: https://github.com/buildroot/buildroot
  REPO_BRANCH: 2025.05
  CONFIG_FILE: seed.config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Buildroot
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_URL }}
          ref: ${{ env.REPO_BRANCH }}

      - name: Checkout custom files
        uses: actions/checkout@v4
        with:
          path: custom

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc wget cpio unzip rsync \
            libncurses-dev file git python3 python3-pip pkg-config \
            libssl-dev libelf-dev bison flex

      - name: Apply defconfig + seed
        run: |
          make pc_x86_64_efi_defconfig
          cp custom/${{ env.CONFIG_FILE }} .config 2>/dev/null || true
          make olddefconfig

      - name: Build
        run: make -j$(nproc)

      - name: Package artifacts
        run: |
          mkdir dist
          cp -a output/images/* dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-pc-uefi-x86_64
          path: dist
